### ISSUE TITLE
Forge 404 when creating project

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-devops#154]
This happens on the newest image with OpenShift 1.0.7 when creating a project (after the screen entering the name (where btw the label is called "Named"):

![screen shot 2015-10-31 at 07 05 59](https://cloud.githubusercontent.com/assets/99080/10862172/33f60616-7f9e-11e5-830a-dbce3976da95.png)

Fabric8 version is 2.2.63

In the forge pod's log, the following is included:

```
--------------------------------------
Both io.fabric8.forge.rest.CommandsResource#getCommandInput and io.fabric8.forge.rest.CommandsResource#getCommandIn
put are equal candidates for handling the current request which can lead to unpredictable results
javax.ws.rs.NotFoundException: No BuildConfig for user/gogsadmin
        at io.fabric8.forge.rest.git.RepositoriesResource.projectRepositoryResource(RepositoriesResource.java:152)
        at io.fabric8.forge.rest.CommandsResource.withUIContext(CommandsResource.java:491)
        at io.fabric8.forge.rest.CommandsResource.getCommandInput(CommandsResource.java:208)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
```

I attached the full log is [here](https://gist.github.com/rhuss/736df9dc8458cd385f29)

**Comment by jstrachan** [comment]
think this is this issue https://github.com/fabric8io/fabric8/issues/5159 I'm just testing a fix - will cut a new release ASAP

**Comment by jstrachan** [comment]
fixed by https://github.com/fabric8io/fabric8/pull/5162 - will cut a release as soon as its merged

**Comment by jstrachan** [comment]
@rhuss just confirmed this is now fixed with the latest release - sorry about that!
