### ISSUE TITLE
App wizard failure - Camel

### ISSUE THREAD

**Issue by tdcox** [fabric8io/fabric8-devops#335]
Using platform deployed with gofabric8 0.4.3:

Creating a new Camel-flavoured app via the wizard fails with:

HTTP ERROR 500
Problem accessing /api/forge/command/execute/devops-edit. Reason: Server Error
org.apache.cxf.interceptor.Fault: http://gogs.vagrant.f8/gogsadmin/test01.git: authentication not supported
	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:162)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:128)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:212)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:816)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1114)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1048)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)

Looks like the Camel Spring Quickstart project is successfully created in Gogs and a Jenkins build pipeline is created, but doesn't run.

**Comment by gashcrumb** [comment]
I've always gotten this when I don't have a gogsadmin secret set up or it's using the wrong username/password, have you verified in the project's settings under 'Secrets' that there's a secret called gogsadmin and that it matches the username/password you used when deploying cd-pipeline?

**Comment by tdcox** [comment]
I created a secret with the default gogsadmin credentials.

I've just performed a re-install of cd-pipeline on a clean vagrant image. After running cd-pipeline, the new information page shows several errors:

Gogs:

kind: Status
apiVersion: v1
metadata: {}
status: Failure
message: the server could not find the requested resource
reason: NotFound
details: {}
code: 404

Gogs-https-admin:
kind: Status
apiVersion: v1
metadata: {}
status: Failure
message: 'namespaces "user-secrets-source-admin" not found'
reason: NotFound
details:
  name: user-secrets-source-admin
  kind: namespaces
code: 404

Jenkins (service):
kind: Status
apiVersion: v1
metadata: {}
status: Failure
message: 'services "jenkins" already exists'
reason: AlreadyExists
details:
  name: jenkins
  kind: services
code: 409

Jenkins (route):
kind: Status
apiVersion: v1
metadata: {}
status: Failure
message: 'routes "jenkins" already exists'
reason: AlreadyExists
details:
  name: jenkins
  kind: routes
code: 409

Everything reports as running.

**Comment by tdcox** [comment]
Testing App Wizard: 

(Note there appears to be some naming inconsistency - the button is now called 'Create App' as opposed to 'Create Project' (which I assume creates a namespace) but the breadcrumb trail and page header say 'Create Project')

On the 'Create a new project' page, hit the integration button and name the project test01. Hit next.

Pipeline tab appears. Spinny wheel for a while, then text boxes. Pipeline build script types don't appear for another few moments, so it may be possible to submit an inconsistent page state here.

Select '---Canary Release and Stage'. Hit next.

Executing message and spinny wheel, followed by HTTP Error 500 as in the initial bug report.

**Comment by tdcox** [comment]
OK, making some progress. The source secrets screen has three fields, Name, Password and User name, where User name defaults to the logged in account (admin). If I edit the secret so that Name AND User name are 'gogsadmin', then I can run a build using the default gogs account. Perhaps we could clarify the naming of these fields to make their question more intuitive to answer? They have info icons with no content at the moment.
