### ISSUE TITLE
Jenkins job is not created when a cdpipeline project is designed using forge

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-devops#52]
Version used : 2.2.35-SNASPHOT of Forge, Jenkins, Gerrit & pipeline

![screenshot 2015-09-28 11 43 26](https://cloud.githubusercontent.com/assets/463790/10132323/305439e2-65d6-11e5-984e-890da3ad1865.png)
![screenshot 2015-09-28 11 43 07](https://cloud.githubusercontent.com/assets/463790/10132324/305680ee-65d6-11e5-8995-e11346af125c.png)
![screenshot 2015-09-28 11 42 56](https://cloud.githubusercontent.com/assets/463790/10132325/30580950-65d6-11e5-9919-1b5071fafde6.png)

This timeout error is reported by the forge docker container

````
INFO: jenkins http://jenkins.vagrant.f8
Sep 28, 2015 8:56:13 AM io.fabric8.devops.connector.DevOpsConnector execute
INFO: About to apply build config: {
    "metadata": {
        "name": "gogsadmin-partners1",
        "annotations": {
            "fabric8.link.environment.gogsadmin-partners1-prod/label": "Production",
            "fabric8.link.environment.gogsadmin-partners1-staging/label": "Staging",
            "fabric8.link.environment.gogsadmin-partners1-prod/url": "http://fabric8.vagrant.f8/kubernetes/pods?namespace=gogsadmin-partners1-prod",
            "fabric8.link.jenkins.job/url": "http://jenkins.vagrant.f8/job/gogsadmin-partners1",
            "fabric8.link.environment.gogsadmin-partners1-staging/url": "http://fabric8.vagrant.f8/kubernetes/pods?namespace=gogsadmin-partners1-staging",
            "fabric8.link.jenkins.job/label": "Job"
        },
        "labels": {
            "repo": "partners1",
            "user": "gogsadmin"
        }
    },
    "apiVersion": "v1",
    "kind": "BuildConfig",
    "spec": {
        "source": {
            "git": {"uri": "http://gogs.vagrant.f8/gogsadmin/partners1.git"},
            "type": "Git"
        },
        "strategy": {
            "type": "Custom",
            "customStrategy": {
                "from": {
                    "kind": "DockerImage",
                    "name": "fabric8/openshift-s2i-jenkins-trigger"
                },
                "env": [
                    {
                        "name": "BASE_URI",
                        "value": "http://jenkins.vagrant.f8"
                    },
                    {
                        "name": "JOB_NAME",
                        "value": "gogsadmin-partners1"
                    }
                ]
            }
        },
        "triggers": [
            {
                "github": {"secret": "secret101"},
                "type": "GitHub"
            },
            {
                "type": "Generic",
                "generic": {"secret": "secret101"}
            }
        ]
    }
}
Sep 28, 2015 8:56:13 AM io.fabric8.kubernetes.api.Controller applyNamespace
INFO: Creating a namespace default
Sep 28, 2015 8:56:13 AM io.fabric8.devops.connector.DevOpsConnector execute
INFO: Created build configuration for gogsadmin-partners1 in namespace: default at https://kubernetes.default.svc.cluster.local/
Sep 28, 2015 8:56:13 AM io.fabric8.devops.connector.DevOpsConnector postJenkinsBuild
INFO: POSTING the jenkins job to: http://172.30.55.212:80/createItem?name=gogsadmin-partners1
Sep 28, 2015 8:58:20 AM io.fabric8.devops.connector.DevOpsConnector postJenkinsBuild
SEVERE: Failed to trigger jenkins on http://172.30.55.212:80/createItem?name=gogsadmin-partners1. java.net.ConnectException: Connection timed out
java.net.ConnectException: Connection timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1168)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:932)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1282)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1257)
        at io.fabric8.devops.connector.DevOpsConnector.postJenkinsBuild(DevOpsConnector.java:1002)
        at io.fabric8.devops.connector.DevOpsConnector.createJenkinsJob(DevOpsConnector.java:924)
        at io.fabric8.devops.connector.DevOpsConnector.execute(DevOpsConnector.java:298)
        at io.fabric8.forge.devops.DevOpsEditStep.execute(DevOpsEditStep.java:340)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
        at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
        at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
        at io.fabric8.forge.devops.DevOpsEditStep_$$_javassist_18666a1f-dc7a-4c36-8d0a-917cd96df19b.execute(DevOpsEditStep_$$_javassist_18666a1f-dc7a-4c36-8d0a-917cd96df19b.java)
        at org.jboss.forge.addon.ui.impl.controller.WizardCommandControllerImpl.execute(WizardCommandControllerImpl.java:153)
        at org.jboss.forge.addon.ui.impl.controller.NoUIWizardControllerDecorator.execute(NoUIWizardControllerDecorator.java:152)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback$2.call(ClassLoaderAdapterCallback.java:123)
        at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
        at org.jboss.forge.furnace.proxy.ClassLoaderAdapterCallback.invoke(ClassLoaderAdapterCallback.java:96)
        at org.jboss.forge.addon.ui.controller.CommandController_$$_javassist_2e10446e-9a89-4d8d-a0eb-2b833a667be8.execute(CommandController_$$_javassist_2e10446e-9a89-4d8d-a0eb-2b833a667be8.java)
        at io.fabric8.forge.rest.CommandsResource.executeCommand(CommandsResource.java:237)
```

**Comment by cmoulliard** [comment]
Fixed with 2.2.36
